all: sequential_implementation student_submission

sequential_implementation:
	g++ -Wall -o sequential_implementation -O3 sequential_implementation.cpp

student_submission:
	g++ -Wall -o student_submission -O3 student_submission.cpp

clean: rm sequential_implementation student_submission